/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                         //
//________/\\\________/\\\________/\\\__/\\\\\\\\\\\\\\\__/\\\\\\\\\\\\\\\__/\\\\\_____/\\\_______________/\\\\\\\\\_____/\\\\\_____/\\\______/\\\\\\\\\\\__/\\\________/\\\____________/\\\\____________/\\\\__/\\\\\\\\\\\\____          //
// _____/\\\\/\\\\____\/\\\_______\/\\\_\/\\\///////////__\/\\\///////////__\/\\\\\\___\/\\\_____________/\\\\\\\\\\\\\__\/\\\\\\___\/\\\_____\/////\\\///__\/\\\_______\/\\\___________\/\\\\\\________/\\\\\\_\/\\\////////\\\__         //
//  ___/\\\//\////\\\__\/\\\_______\/\\\_\/\\\_____________\/\\\_____________\/\\\/\\\__\/\\\____________/\\\/////////\\\_\/\\\/\\\__\/\\\_________\/\\\_____\/\\\_______\/\\\___________\/\\\//\\\____/\\\//\\\_\/\\\______\//\\\_        //
//   __/\\\______\//\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\_____\/\\\\\\\\\\\_____\/\\\//\\\_\/\\\___________\/\\\_______\/\\\_\/\\\//\\\_\/\\\_________\/\\\_____\/\\\_______\/\\\___________\/\\\\///\\\/\\\/_\/\\\_\/\\\_______\/\\\_       //
//    _\//\\\______/\\\__\/\\\_______\/\\\_\/\\\///////______\/\\\///////______\/\\\\//\\\\/\\\___________\/\\\\\\\\\\\\\\\_\/\\\\//\\\\/\\\_________\/\\\_____\/\\\_______\/\\\___________\/\\\__\///\\\/___\/\\\_\/\\\_______\/\\\_      //
//     __\///\\\\/\\\\/___\/\\\_______\/\\\_\/\\\_____________\/\\\_____________\/\\\_\//\\\/\\\___________\/\\\/////////\\\_\/\\\_\//\\\/\\\_________\/\\\_____\/\\\_______\/\\\___________\/\\\____\///_____\/\\\_\/\\\_______\/\\\_     //
//      ____\////\\\//_____\//\\\______/\\\__\/\\\_____________\/\\\_____________\/\\\__\//\\\\\\___________\/\\\_______\/\\\_\/\\\__\//\\\\\\__/\\\___\/\\\_____\//\\\______/\\\____________\/\\\_____________\/\\\_\/\\\_______/\\\__    //
//       _______\///\\\\\\___\///\\\\\\\\\/___\/\\\\\\\\\\\\\\\_\/\\\\\\\\\\\\\\\_\/\\\___\//\\\\\___________\/\\\_______\/\\\_\/\\\___\//\\\\\_\//\\\\\\\\\_______\///\\\\\\\\\/_____________\/\\\_____________\/\\\_\/\\\\\\\\\\\\/___   //
//        _________\//////______\/////////_____\///////////////__\///////////////__\///_____\/////____________\///________\///__\///_____\/////___\/////////__________\/////////_______________\///______________\///__\////////////_____  //
//                                                                                                                                                                                                                                         //
//                                           ===========================================================*CREATED BY GAMING RASH*=====================================================                                                      //
//                                                                                                                                                                                                                                         //       
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}
module.exports = {
SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkV3NC92Y0wwRzJWNzR1T1dRU2xtM25PSlFiL2VYZnRES1FkT3p1K2pVRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibThmQkRDYUgzTXllR1FtZklVYTA2aWFxTEhURnRqVSt0eFdmUkxZWi9udz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpRDRaSS9yUldKdEN4Ri9pa1hic1d4KzUreExBV2piYlJrZHQxRDV0QmtJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJQM3Z0Y3pmd3lUZThJbmVJQlBLWGhDZmxrMjUzeTBHNlprWFJVbExpSWhjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklBYStuNXg4bXlXOEpQRlBydWJtdWZxZlE4VWUzdWYxa0N2T1g2cndBa1k9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxGYXVQUnFlanNCYjVOMEYza2NQZmtSNXFmWEU4dngzanBTZVd1ZkkzMEU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkhSZ0NUTFhScjAxMk1vdFVza2FEOUVLaVlGVlhZdkI1dU9mWEVISUYyaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS2E5cERpc1pBcUR2Qjh4TjFFdHV5YmpkWVBjakx2R0MxQ1lCcmxqaHBBND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVkdjRzeUNIeFVtanpFV1EyblE4MHEwcVRzdTM2N2N2R0dPdkkrN3pubG5XQ0NYLy9PUWVybVJnaFJlODdFcWRFZjlyVGxiYi8zem9XTk9uempBUWp3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE5LCJhZHZTZWNyZXRLZXkiOiJRdi84R3FCRzd4MUhjUG5WNDhCVng5NDVXTW9TRWR1RHVsMmx0Y2FrdDNRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJwRm5HbGItQlFoYTBBVFVqSm5VOHVBIiwicGhvbmVJZCI6IjZmZjE1MzNmLWEyMTUtNGYyMy1iNGZhLWRhZDI4MmFkOTMyZCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBRW50Z3BTZ1BaUitlQkRFOUU0VWxwditaNE09In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia011NUhrei8vNitNc2F5aFZ0blRpYnZHQ1BvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjNGUVI0RjJYIiwibWUiOnsiaWQiOiI5NDc0Mjc5MTE1MzozQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdkI7Kn+G0hSDwnZCS4bSb4bSA4bSb4bSc6pyxIPCdkIrJqsm0yaIg8J2QkuG0gOG0gOG0ismqIPCdkIHKmcqcIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPV29uSkFFRU95RDU3a0dHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJmYVRHR1V4L2NMVUlNcmw5d2Q2QkhubmRiMzE1c1lwTjkvaU93M3Z2aG5JPSIsImFjY291bnRTaWduYXR1cmUiOiJNQnd0Y2R3c2xvMjRKQWxYMG9nZG9LdjhUWXBhTVd2ZTErWlFKWU5sWkk5WEt1U2xPbjRkNHNnS0h0QU1SVkczOGtFUll5UWF4cDhLS21wL0FydzVBQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWURYVmE1bUFZU01odkVPcnRqWTYxbzRYK3VieUV4SG13d2NZamFoK2pLT1B1dmtIVkxyZ05JTW02UEluVWY4RUNmTjhrUld6WkwxS0lXSjNPenJjaEE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc0Mjc5MTE1MzozQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlgya3hobE1mM0MxQ0RLNWZjSGVnUjU1M1c5OWViR0tUZmY0anNONzc0WnkifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE4Mzg0NTcsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRDRLIn0=",
};